import type { Metadata } from "next";
import "./globals.css";
import { getWebsiteData } from "@/lib/hygraph";
import { DataProvider } from "@/context/DataContext";
import Header from "@/components/Header";
import { Roboto, Orbitron } from "next/font/google";

const roboto = Roboto({
  subsets: ["latin"],
  variable: "--font-roboto", // Custom variable name for Roboto Flex
  display: "swap",
});

const orbitron = Orbitron({
  subsets: ["latin"],
  variable: "--font-orbitron", // Custom variable name for Orbitron
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { website } = await getWebsiteData();

  return (
    <html
      lang="en"
      className={`${roboto.variable} ${orbitron.variable} touch-manipulation touch-auto`}
    >
      <body className="bg-slate-100">
        <DataProvider website={website}>
          <Header />
          <div className="font-[roboto] flex-col mx-auto pt-[80px] bg-white max-w-[1920px]">
            <main>{children}</main>
          </div>
        </DataProvider>
      </body>
    </html>
  );
}
